import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SignIn from './signin.js'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>T R Y A D M I N</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <SignIn />
    </div>
  )
}
